import { Link } from 'react-router-dom';
import GlassCard from '../components/GlassCard';
import Button from '../components/Button';
import { FaMicrophone, FaShieldAlt, FaGithub, FaChrome, FaArrowRight } from 'react-icons/fa';
import { SiTensorflow } from 'react-icons/si';

const FeatureCard = ({ icon, title, children }) => (
  <div className="glass p-6 hover:bg-white/5 transition-colors duration-300 h-full">
    <div className="text-brand-400 text-2xl mb-3">{icon}</div>
    <h3 className="font-semibold text-xl mb-2">{title}</h3>
    <p className="text-white/80">{children}</p>
  </div>
);

const ChallengeCard = ({ title, items }) => (
  <div className="glass p-6 hover:bg-white/5 transition-colors duration-300">
    <h3 className={`font-semibold text-xl mb-3 ${title.includes('Challenges') ? 'text-red-300' : 'text-blue-400'}`}>
      {title}
    </h3>
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start">
          <span className="text-red-400 mr-2">•</span>
          <span className="text-white/80">{item}</span>
        </li>
      ))}
    </ul>
  </div>
);

export default function Landing() {
  const features = [
    {
      icon: <FaMicrophone />,
      title: 'AI Audio Detection',
      description: 'Upload audio clips to detect if they were generated by AI with our advanced transformer-based model.'
    },
    {
      icon: <FaShieldAlt />,
      title: 'Real-time Analysis',
      description: 'Get instant results with confidence percentages in a clean, modern browser extension interface.'
    },
    {
      icon: <SiTensorflow />,
      title: 'Advanced Technology',
      description: 'Built with cutting-edge machine learning models to stay ahead of evolving AI voice synthesis.'
    }
  ];

  const challenges = {
    title: 'Challenges & Considerations',
    items: [
      'Model accuracy with subtle audio differences',
      'Generalization across languages and accents',
      'Performance in browser environment',
      'Ethical implications of AI detection'
    ]
  };

  const strengths = {
    title: 'Key Strengths',
    items: [
      'Timely solution for AI-generated audio detection',
      'User-friendly browser extension',
      'Modular architecture for easy updates',
      'Open-source and community-driven'
    ]
  };

  return (
    <main className="mx-auto max-w-6xl px-4 py-12">
      {/* Hero Section */}
      <section className="text-center py-20">
        <h1 className="text-4xl md:text-6xl font-extrabold mb-6">
          <span 
            className="relative bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 bg-clip-text text-transparent bg-300% animate-gradient"
            style={{
              textShadow: '0 0 10px rgba(96, 165, 250, 0.7), 0 0 20px rgba(59, 130, 246, 0.5)'
            }}
          >
            TrueVoice
          </span>
        </h1>
        <p className="text-xl text-white/80 max-w-3xl mx-auto mb-8">
          Detect AI-generated audio with confidence. Our browser extension helps you distinguish between real and synthetic voices.
        </p>
        <div className="flex flex-wrap justify-center gap-4 mb-16">
          <Button
            as={Link}
            to="/login"
            variant="primary"
            className="px-8 py-3 text-lg"
            iconRight
          >
            Try Demo
          </Button>
          <Button
            as="a"
            href="https://github.com/userkace/true-voice"
            target="_blank"
            rel="noopener noreferrer"
            variant="ghost"
            icon={FaGithub}
          >
            View on GitHub
          </Button>
        </div>

        <div className="mx-auto">
          <h2 className="text-2xl font-bold text-center mb-12">How It Works</h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: '1',
                title: 'Install Extension',
                description: 'Add our browser extension to Chrome or Edge in just a few clicks.'
              },
              {
                icon: '2',
                title: 'Upload Audio',
                description: 'Easily upload audio files or record directly from your microphone.'
              },
              {
                icon: '3',
                title: 'Get Analysis',
                description: 'Receive instant results with confidence scores and detailed insights.'
              }
            ].map((feature, i) => (
              <div key={i} className="glass p-6 hover:bg-white/5 transition-colors duration-300 h-full">
                <div className="text-brand-400 text-2xl font-bold mb-3">{feature.icon}</div>
                <h3 className="font-semibold text-xl mb-2">{feature.title}</h3>
                <p className="text-white/80">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-16">
        <h2 className="text-3xl font-bold text-center mb-12">Key Features</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {features.map((feature, i) => (
            <FeatureCard key={i} icon={feature.icon} title={feature.title}>
              {feature.description}
            </FeatureCard>
          ))}
        </div>
      </section>

      {/* Technical Details */}
      <section className="grid lg:grid-cols-2 gap-8 mb-20">
        <ChallengeCard {...challenges} />
        <ChallengeCard {...strengths} />
      </section>

      {/* CTA */}
      {/* <section className="text-center py-16">
        <h2 className="text-3xl font-bold mb-6">Ready to Detect AI-Generated Audio?</h2>
        <p className="text-white/80 mb-8 max-w-2xl mx-auto">
          Join the fight against AI-generated disinformation. Try TrueVoice today and experience the future of audio authentication.
        </p>
        <div className="flex flex-wrap justify-center gap-4">
          <Button
            as={Link}
            to="/login"
            variant="primary"
            className="px-8 py-3 text-lg"
            icon={FaChrome}
            iconRight
          >
            Add to Chrome
          </Button>
          <Button
            as="a"
            href="#features"
            variant="ghost"
            icon={FaArrowRight}
          >
            Learn More
          </Button>
        </div>
      </section> */}
    </main>
  );
}